import { Geist, Geist_Mono, Oxanium } from "next/font/google";
import "./globals.css";


const oxanium = Oxanium({
  variable : "--font-oxanium",
  subsets: ["latin"]
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  className={`${oxanium.variable} antialiased font-oxanium`}>
        {children}
      </body>
    </html>
  );
}
